### ISSUE TITLE
Make shift end location optional or have several types

### ISSUE THREAD

**Issue by diogo-nogueira** [reinterpretcat/vrp#111]
Hi @reinterpretcat , This project has been amazing with the variety of problem solving it offers and i've been really loving it.

I have been using the python pip package and was wondering if it was possible to make the end location of a shift optional and during the problem solving the arrival stop location becomes the same as the last stop that was serviced or simply dont insert a arrival stop.

Since currently when using the shift end property the travel time to the end location is also used in the total tour time if that travel time is 1 hour (or more) then that's 1 hour (or more) that cant be used to complete a job or service more jobs, this becomes a problem with some work contracts with third party companies that offer a certain amount of service hours and dont take into account the travel time of the worker back to base that makes the solutions returned by the solver not very cost efficient.

I've tried to work around the problem using job time windows but that still causes problems when using multiple vehicles that have different shift start and end times.

Another use case is when the vehicle has to stay overnight in a motel (or another to be determined location) near the location of the last serviced job then continue next day from the same location since its hard to know were the last location is going to be a end location is also going to cause problems so its safer to assume the last stop is going to be relatively close to the motel and in this case the start location also has to be optional (only first shift location is required) when solving multiple days but you can workaround this issue by solving days individualy (doing several calls to vrp_cli) and using the results from the last solution to set the start location of each vehicle when creating the next problems.

Adding types to the shifts can also solve this issue:

**Type location**: Same as current implementation.
```
"end": {
  "latest": "2023-07-04T18:00:00Z",
  "type": "location",
  "location": {
    "lat": 52.5316,
    "lng": 13.3884
  }
}
```

**Type lastJob**: Sets the location of the arrival stop the same as the last served job stop.

```
"end": {
  "latest": "2023-07-04T18:00:00Z",
  "type": "lastJob"
}
```

**Type nearest**: Chooses the closest set of coordenates from the last served job stop (can be used to return the vehicle to the closest depot).

```
"end": {
  "latest": "2023-07-04T18:00:00Z",
  "type": "nearest",
  "location": [
    {
      "lat": 52.5316,
      "lng": 13.3884
    },
    {
      "lat": 54.8462,
      "lng": 13.9671
    },
    {
      "lat": 53.4712,
      "lng": 12.5517
    },
  ]
}
```

The start shift could also use the types "location", "nearest" but the "closest" type is exclusive to the end shift and "location"
being always required in the first start of the shifts.

To prevent breaking changes for people already using the vrp, the "type" would be "location" when not defined.

I know the types would be alot more work to implement, simply being able to have the end shift location optional would awsome.

**Comment by reinterpretcat** [comment]
Hi,
thanks for feedback!

Actually, shift.end is already optional and can be omitted to model open VRP. Additionally, if you want to limit working hours of a vehicle, you can specify vehicle.limits.maxDuration.

Regarding multi-shift and next day: yes, this is not yet supported. The main complexity is that the solver currently can plan multiple shifts of the same vehicle in parallel as start is always known from the beginning. Dynamic start location would require some implicit dependency between different shifts which is not straightforward how to implement taking into account how heuristic works. So, it is not yet supported. Potential workaround could be using one shift and reload, but this will be a bit less efficient I guess..

Anyway, thanks for proposal: I might consider it one day. At the moment, I'm experimenting more with improvements in heuristics, rather than adding new features.

**Comment by diogo-nogueira** [comment]
In other vrps i was so used to using shifts to set work hours that i didnt even think of using limits, thanks for pointing that out.
