### ISSUE TITLE
Define break interval

### ISSUE THREAD

**Issue by dooley** [reinterpretcat/vrp#24]
`time window or interval after which a break should happen (e.g. between 3 or 4 hours after start)`

Can you please explain, how to define break intervals? I.e. every 4 hours? Documentation is not clear and i can't find any example.

BTW, great tool.

**Comment by reinterpretcat** [comment]
Hi, thanks for feedback!

Interval break is defined similar to normal:

```
"breaks": [{
      "time": [12600, 14400],
      "duration": 3600
}]
```
You specify time interval in seconds since departure, the solver will try to schedule break in this interval. However, break is soft constrain and can be skipped (then it goes to `violations` property in solution). To make it more desirable, you can override default objective function and set `breaks` property on `minimize-unassigned` objective (see https://reinterpretcat.github.io/vrp/concepts/pragmatic/problem/objectives.html).

Please note that interval break is experimental feature: requires more testing.

**Comment by dooley** [comment]
Thank you. Yes, i'm aware breaks are experimental.
