### ISSUE TITLE
Pip install

### ISSUE THREAD

**Issue by jenswollenweber** [reinterpretcat/vrp#97]
I have a clean Windows 10 version with Python 3.11.2. 
In general PIP works properly, but when I try to install VRP-CLI by
"pip install vrp-cli"
I get the errors: 
"Could not find a version that satisfies the vrp-cli (from versions: none)
No matching distribution found for vrp-cli"
I am quite a python newbie, so any advices are appreciated.

**Comment by reinterpretcat** [comment]
The problem is related to Windows: the version I've built and distribute is targeting manylinux distribution. To make the pip version working on Windows, I would need to cross-compile it as described here:

https://www.maturin.rs/distribution.html#cross-compile-to-windows

Theoretically, you can build it locally: https://reinterpretcat.github.io/vrp/examples/interop/python.html#using-maturin and use without installing it from PyPi

**Comment by reinterpretcat** [comment]
I've built dedicated github actions which should build now a proper distribution
